create table roles (
    id bigint generated by default as identity primary key,
    name varchar(50) not null unique,
    description varchar(255),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table users (
    id bigint generated by default as identity primary key,
    full_name varchar(120) not null,
    email varchar(150) not null unique,
    password_hash varchar(255) not null,
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table user_roles (
    user_id bigint not null,
    role_id bigint not null,
    primary key (user_id, role_id),
    constraint fk_user_roles_user foreign key (user_id) references users (id) on delete cascade,
    constraint fk_user_roles_role foreign key (role_id) references roles (id) on delete cascade
);
