create table areas (
    id bigint generated by default as identity primary key,
    name varchar(120) not null unique,
    description varchar(255),
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table sites (
    id bigint generated by default as identity primary key,
    name varchar(120) not null unique,
    description varchar(255),
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table positions (
    id bigint generated by default as identity primary key,
    area_id bigint not null,
    name varchar(120) not null,
    description varchar(255),
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_positions_area foreign key (area_id) references areas (id),
    constraint uk_positions_area_name unique (area_id, name)
);

create table employees (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique,
    position_id bigint not null,
    site_id bigint not null,
    dni varchar(20) not null unique,
    phone varchar(30),
    hire_date date not null,
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_employees_user foreign key (user_id) references users (id),
    constraint fk_employees_position foreign key (position_id) references positions (id),
    constraint fk_employees_site foreign key (site_id) references sites (id)
);
