create table attendance_settings (
    id bigint generated by default as identity primary key,
    workday_start_time time not null,
    workday_end_time time not null,
    late_tolerance_minutes integer not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

insert into attendance_settings (workday_start_time, workday_end_time, late_tolerance_minutes)
values ('09:00:00', '18:00:00', 10);

create table attendance_records (
    id bigint generated by default as identity primary key,
    employee_id bigint not null,
    attendance_date date not null,
    check_in_at timestamp,
    check_out_at timestamp,
    status varchar(30) not null,
    late_minutes integer not null default 0,
    source varchar(30) not null,
    notes varchar(500),
    justification_note varchar(500),
    justified_by_user_id bigint,
    justified_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_attendance_records_employee foreign key (employee_id) references employees (id),
    constraint fk_attendance_records_justified_by_user foreign key (justified_by_user_id) references users (id),
    constraint uk_attendance_employee_date unique (employee_id, attendance_date)
);

create table leave_requests (
    id bigint generated by default as identity primary key,
    employee_id bigint not null,
    request_type varchar(40) not null,
    start_at timestamp not null,
    end_at timestamp not null,
    reason varchar(500) not null,
    status varchar(30) not null,
    reviewed_by_user_id bigint,
    reviewed_at timestamp,
    review_comment varchar(500),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_leave_requests_employee foreign key (employee_id) references employees (id),
    constraint fk_leave_requests_reviewed_by_user foreign key (reviewed_by_user_id) references users (id)
);
