create table vacation_balances (
    id bigint generated by default as identity primary key,
    employee_id bigint not null unique,
    available_days integer not null default 0,
    used_days integer not null default 0,
    pending_days integer not null default 0,
    notes varchar(500),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_vacation_balances_employee foreign key (employee_id) references employees (id)
);

create table vacation_requests (
    id bigint generated by default as identity primary key,
    employee_id bigint not null,
    start_date date not null,
    end_date date not null,
    requested_days integer not null,
    observation varchar(500),
    status varchar(30) not null,
    reviewed_by_user_id bigint,
    reviewed_at timestamp,
    review_comment varchar(500),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_vacation_requests_employee foreign key (employee_id) references employees (id),
    constraint fk_vacation_requests_reviewed_by_user foreign key (reviewed_by_user_id) references users (id)
);

create table contracts (
    id bigint generated by default as identity primary key,
    employee_id bigint not null,
    contract_type varchar(30) not null,
    start_date date not null,
    end_date date,
    status varchar(30) not null,
    notes varchar(500),
    previous_contract_id bigint,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_contracts_employee foreign key (employee_id) references employees (id),
    constraint fk_contracts_previous foreign key (previous_contract_id) references contracts (id)
);
