create table contract_documents (
    id bigint generated by default as identity primary key,
    contract_id bigint not null,
    file_name varchar(255) not null,
    content_type varchar(120) not null,
    file_size bigint not null,
    file_data bytea not null,
    uploaded_at timestamp not null default current_timestamp,
    constraint fk_contract_documents_contract foreign key (contract_id) references contracts (id)
);

create index idx_contract_documents_contract_id on contract_documents (contract_id);
